[package]
name = "polkadot-node-collation-generation"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
futures = "0.3.19"
tracing = "0.1.29"
polkadot-node-subsystem = { path = "../subsystem" }
polkadot-node-subsystem-util = { path = "../subsystem-util" }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "2c4549689dbb86c23725dac2f82af35faa07c9f6" }
sp-maybe-compressed-blob  = { git = "https://github.com/paritytech/substrate", rev = "2c4549689dbb86c23725dac2f82af35faa07c9f6" }
thiserror = "1.0.30"
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["bit-vec", "derive"] }

cirrus-node-primitives = { path = "../../../crates/cirrus-node-primitives" }
sp-executor  = { path = "../../../crates/sp-executor" }
subspace-runtime-primitives = { path = "../../../crates/subspace-runtime-primitives" }
