[package]
name = "polkadot-node-jaeger"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Polkadot Jaeger primitives"

[dependencies]
async-std = "1.8.0"
mick-jaeger = "0.1.6"
lazy_static = "1.4"
parking_lot = "0.12.0"
sc-network = { git = "https://github.com/paritytech/substrate", rev = "2c4549689dbb86c23725dac2f82af35faa07c9f6" }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "2c4549689dbb86c23725dac2f82af35faa07c9f6" }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "2c4549689dbb86c23725dac2f82af35faa07c9f6" }
thiserror = "1.0.30"
log = "0.4.13"
parity-scale-codec = { version = "2.3.1", default-features = false }

subspace-runtime-primitives = { path = "../../../crates/subspace-runtime-primitives" }
