[package]
name = "subspace-networking"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
description = "Networking functionality of Subspace Network, primarily used for DSN (Distributed Storage Network)"
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
event-listener-primitives = "2.0.1"
parking_lot = "0.12.0"
thiserror = "1.0.30"
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread"] }

[dependencies.libp2p]
version = "0.42.0"
default-features = false
features = [
    "dns-tokio",
    "gossipsub",
    "identify",
    "kad",
    "noise",
    "ping",
    "tcp-tokio",
    "websocket",
    "yamux"
]
